# Generated by Django 6.0.5 on 2026-05-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], default='Sale', max_length=20),
        ),
    ]
