# Generated by Django 6.0.5 on 2026-05-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
