# Generated by Django 6.0.5 on 2026-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='map_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
