# Generated by Django 6.0.5 on 2026-05-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_property_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
