# Generated by Django 6.0.5 on 2026-05-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_propertyimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
