# Generated by Django 6.0.5 on 2026-05-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_property_is_featured_property_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('owner', 'Owner')], default='buyer', max_length=20),
        ),
    ]
